version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: django
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: django_db
    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./static/css/style.css:/code/static/css/style.css
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: