# Generated by Django 3.2.19 on 2023-07-01 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
        migrations.AddField(
            model_name='notification',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
