# Generated by Django 3.2.19 on 2023-07-15 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
            preserve_default=False,
        ),
    ]
