# Generated by Django 3.2.19 on 2023-07-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(default='宮崎県', max_length=100),
            preserve_default=False,
        ),
    ]
