# Generated by Django 3.2.20 on 2023-07-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_messa'),
    ]

    operations = [
        migrations.AddField(
            model_name='messa',
            name='item',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
            preserve_default=False,
        ),
    ]
