# Generated by Django 3.2.20 on 2023-08-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_messa_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='messa',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.messa'),
        ),
    ]
