# Generated by Django 3.2.20 on 2023-08-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
